### ISSUE TITLE
Wrong Result

### ISSUE THREAD

**Issue by GitHubNoskcaj211** [lycantropos/quickselect#1]
Hello. Was using this module and found an example where floyd_rivest.nth_largest produced the wrong result. Some of the elements duplicated on the passed in list (not sure what is causing this), causing the nth largest to become inaccurate.
To reproduce checkout this repo:
https://github.com/GitHubNoskcaj211/floyd_rivest_wrong_test_case

**Comment by GitHubNoskcaj211** [comment]
Upon further investigation, this appears to be happening when a pivot being selected is the maximum value for the subsequence. Swapping the gt operator for ge operator fixes the partition function and produces the correct result.

**Comment by GitHubNoskcaj211** [comment]
Also in the testing the duplication behavior is only seen during the `if stop - start > 600:` logic.

**Comment by lycantropos** [comment]
Hi, can you please provide a minimal reproducible example without pickled data? something safer like JSON or plain Python array literal will do and I'll look into that, thanks.

**Comment by GitHubNoskcaj211** [comment]
Yes that was pretty suspect - I updated the github repo with a way to generate a bad example and a bad example already in there. I also found what the issue was - the`candidate, pivot = sequence[n], keys[n]` was stale under certain conditions when the stop - start sequence started. I put in a fix and it appears to work now.

**Comment by lycantropos** [comment]
fix is available starting from [v0.2.1](https://pypi.org/project/quickselect/0.2.1/), thanks @GitHubNoskcaj211 for an issue and PR
